# GitHub Actions modified from
# https://github.com/r-lib/actions/tree/master/examples#standard-ci-workflow

on:
  push:
    branches: [main, master, devel]
  pull_request:
    branches: [main, master, devel]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install Ghostscript (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install --yes ghostscript

      - name: Install Ghostscript (macOS)
        if: runner.os == 'macOS'
        run: brew install ghostscript

      - name: Install Ghostscript (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ghostscript --no-progress --version 10.3.1;
          Add-Content $env:GITHUB_PATH "C:\Program Files\gs\gs10.3.1\bin\";
          refreshenv;
        shell: pwsh

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_INSTALLER: TinyTeX

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual", "--compact-vignettes=both")'

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.config.r }}-results
          path: check

  test-coverage:
    needs: R-CMD-check

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
